/*
 * ======================================
 * 01_schema.sql
 * (This is the FINAL, 100% CORRECTED file)
 * All tables now explicitly use 'ENGINE=InnoDB'
 * to guarantee transactions and ROLLBACK will work.
 * ======================================
 */

-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS judicial_system;
USE judicial_system;

-- Drop tables in reverse order of creation to avoid foreign key issues
DROP TABLE IF EXISTS REPRESENTS;
DROP TABLE IF EXISTS DEALS;
DROP TABLE IF EXISTS PRECIDE;
DROP TABLE IF EXISTS HEARING;
DROP TABLE IF EXISTS JUDGEMENT;
DROP TABLE IF EXISTS LAW_SECTION;
DROP TABLE IF EXISTS `CASE`;
DROP TABLE IF EXISTS JUDGE;
DROP TABLE IF EXISTS COURT;
DROP TABLE IF EXISTS LAWYER;
DROP TABLE IF EXISTS LITIGANT;
DROP TABLE IF EXISTS USERS; -- Added USERS table

-- Create tables in order of dependency

CREATE TABLE COURT (
    COURT_ID INT PRIMARY KEY AUTO_INCREMENT,
    COURT_NAME VARCHAR(255) NOT NULL,
    COURT_TYPE VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    PINCODE VARCHAR(10)
) ENGINE=InnoDB;

CREATE TABLE JUDGE (
    JUDGE_ID INT PRIMARY KEY NOT NULL,
    COURT_ID INT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    APPOINTMENT_DATE DATE,
    FOREIGN KEY(COURT_ID) REFERENCES COURT(COURT_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE LAWYER (
    BAR_COUNCIL_ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    AGE INT,
    LINE1 VARCHAR(255),
    LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    PINCODE VARCHAR(10),
    PHONE_NUMBER VARCHAR(15) UNIQUE
) ENGINE=InnoDB;

CREATE TABLE LITIGANT (
    LITIGANT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    AGE INT,
    LINE1 VARCHAR(255),
    LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    PINCODE VARCHAR(10),
    PHONE_NUMBER VARCHAR(15)
) ENGINE=InnoDB;

CREATE TABLE LAW_SECTION (
    SECTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACT_NAME VARCHAR(255) NOT NULL,
    SECTION_NUMBER VARCHAR(50) NOT NULL,
    SECTION_TITLE VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `CASE` (
    CASE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CASE_TITLE VARCHAR(255) NOT NULL,
    CASE_TYPE VARCHAR(100),
    STATUS VARCHAR(50),
    DATE_FILED DATE,
    COURT_ID INT,
    APPEAL_CASE_ID INT,
    FOREIGN KEY (COURT_ID) REFERENCES COURT(COURT_ID) ON DELETE CASCADE,
    FOREIGN KEY (APPEAL_CASE_ID) REFERENCES `CASE`(CASE_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE JUDGEMENT (
    JUDGEMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    CASE_ID INT UNIQUE,
    JUDGE_ID INT,
    DATE DATE,
    OUTCOME VARCHAR(255),
    DESCRIPTION TEXT,
    FOREIGN KEY (CASE_ID) REFERENCES `CASE`(CASE_ID) ON DELETE CASCADE,
    FOREIGN KEY (JUDGE_ID) REFERENCES JUDGE(JUDGE_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE HEARING (
    HEARING_ID INT PRIMARY KEY AUTO_INCREMENT,
    CASE_ID INT,
    DATE DATE,
    SUMMARY TEXT,
    FOREIGN KEY (CASE_ID) REFERENCES `CASE`(CASE_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PRECIDE (
    HEARING_ID INT,
    CASE_ID INT,
    JUDGE_ID INT,
    PRIMARY KEY (HEARING_ID, CASE_ID, JUDGE_ID),
    FOREIGN KEY (HEARING_ID) REFERENCES HEARING(HEARING_ID) ON DELETE CASCADE,
    FOREIGN KEY (CASE_ID) REFERENCES `CASE`(CASE_ID) ON DELETE CASCADE,
    FOREIGN KEY (JUDGE_ID) REFERENCES JUDGE(JUDGE_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DEALS (
    SECTION_ID INT,
    CASE_ID INT,
    PRIMARY KEY (SECTION_ID, CASE_ID),
    FOREIGN KEY (SECTION_ID) REFERENCES LAW_SECTION(SECTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (CASE_ID) REFERENCES `CASE`(CASE_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE REPRESENTS (
    CASE_ID INT,
    BAR_COUNCIL_ID VARCHAR(50),
    LITIGANT_ID INT,
    PRIMARY KEY (CASE_ID, BAR_COUNCIL_ID, LITIGANT_ID),
    FOREIGN KEY (CASE_ID) REFERENCES `CASE`(CASE_ID) ON DELETE CASCADE,
    FOREIGN KEY (BAR_COUNCIL_ID) REFERENCES LAWYER(BAR_COUNCIL_ID) ON DELETE CASCADE,
    FOREIGN KEY (LITIGANT_ID) REFERENCES LITIGANT(LITIGANT_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE USERS (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('lawyer', 'admin', 'public') NOT NULL DEFAULT 'public',
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    bar_council_id VARCHAR(50) NULL,
    FOREIGN KEY (bar_council_id) REFERENCES LAWYER(BAR_COUNCIL_ID) ON DELETE SET NULL
) ENGINE=InnoDB;